"""init

Revision ID: b6fed66ee366
Revises:
Create Date: 2025-09-19 04:03:25.934878

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b6fed66ee366"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
